@startuml
   start
   :<b>Composer Autoloader</b>;
       if (is there a autoload section in a composer.json?) then (true)
           :Load class according composer.json autoload section;
           stop
       else (false)
           :<b>Backwards Compatibility Autoloader</b>;
           -->
           if (class can be resolved to the unified namespace equivalent class) then (true)
               :trigger Composer Autoloader;
               stop
           else (false)
               :<b>Module Autoloader</b>;
               if (class found in module metadata files array?) then (true)
                   :Load class from path defined in metadata;
                   stop
               else (false)
                   if (class found in module metadata extends array?) then (true)
                       :Create extension chains;
                       stop
                   else (false)
                       :Loads any other registered autoloader or a
                       Class not found fatal error is thrown;
                       stop
                   endif
               endif
           endif
       endif
    @enduml