.. uml::

   @startuml
    top to bottom direction

    state "Non Existing" as NonExisting : State where module\nin OXID eShop does \nnot exist yet.

    state Installed: Module files and \nconfiguration files \nin place.

    state Configured: State where the OXID \neShop administrator \nalready configured a \nmodule via OXID eShop \nadmin, or by editing \nconfiguration files. \nDatabase gets not \ntouched.

    state Active : When module being \nactivated, the data \ngoes from configuration \nfiles to the database. \nAt this module becomes \nactive.

    
    [*] --> NonExisting
    NonExisting --> Installed: **Installation**\nvia <i> composer install</i>
    Installed --> Configured: Configure module \nvia eShop admin \nor configuration files
    Configured --> Active : Module activation \nvia eShop admin \nweb interface\nor CLI command
   @enduml