   @startuml

   OxidEsales\EshopCommunity\Application\Model\Article <|-- OxidEsales\EshopProfessional\Application\Model\Article
   OxidEsales\EshopProfessional\Application\Model\Article <|-- OxidEsales\Eshop\Application\Model\Article

   OxidEsales\Eshop\Application\Model\Article - oxarticle : class_alias

   @enduml